/**
 * Types for the Cloudflare bindings declared in wrangler.jsonc.
 * `@opennextjs/cloudflare`'s getCloudflareContext() returns `env` typed as
 * the global CloudflareEnv interface. Regenerate with `npm run cf-typegen`.
 */
declare global {
  interface CloudflareEnv {
    /** D1 database (drizzle-orm/d1) */
    DB: import("@cloudflare/workers-types").D1Database;
    /** Cloudflare Email Workers outbound binding */
    SEND_EMAIL: import("@cloudflare/workers-types").SendEmail;
    /** Static assets generated by OpenNext */
    ASSETS: import("@cloudflare/workers-types").Fetcher;
    /** Self-reference service binding (OpenNext internals + cron routing) */
    WORKER_SELF_REFERENCE: import("@cloudflare/workers-types").Fetcher;
    NEXT_PUBLIC_APP_URL?: string;
    EMAIL_FROM?: string;
    CRON_SECRET?: string;
  }
}

declare module "cloudflare:email" {
  export class EmailMessage {
    constructor(from: string, to: string, raw: string | ReadableStream);
    readonly from: string;
    readonly to: string;
  }
}

export {};
