/**
 * Custom Workers entrypoint wrapping the OpenNext-generated handler.
 * Adds cron trigger routing (replacing vercel.json crons): each schedule in
 * wrangler.jsonc `triggers.crons` is mapped to a Next.js cron API route and
 * invoked through the self-reference service binding with the CRON_SECRET
 * bearer token the routes already expect.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";
import { EmailMessage } from "cloudflare:email";

// `cloudflare:email` is only resolvable in the wrangler-bundled entrypoint,
// not inside the Next.js server bundle — expose it for lib/email/send-email.ts.
(globalThis as Record<string, unknown>).__CF_EMAIL_MESSAGE__ = EmailMessage;

const CRON_ROUTES: Record<string, string> = {
  "0 0 * * *": "/api/cron/sync-markets",
  "15 0 * * *": "/api/cron/refresh-quotes",
};

export default {
  fetch: handler.fetch,

  async scheduled(
    controller: { cron: string },
    env: CloudflareEnv,
    ctx: { waitUntil(promise: Promise<unknown>): void },
  ) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.warn(`No cron route mapped for schedule "${controller.cron}"`);
      return;
    }
    const headers: Record<string, string> = {};
    if (env.CRON_SECRET) {
      headers["authorization"] = `Bearer ${env.CRON_SECRET}`;
    }
    ctx.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(`https://self.internal${path}`, { headers }).then(
        (res: Response) => console.log(`Cron ${path} -> ${res.status}`),
      ),
    );
  },
};
