-- Reconstructed from meta/0007_snapshot.json.
--
-- This file was generated by drizzle-kit and applied to the databases, but was
-- never committed: the journal and the snapshot referenced it while the SQL
-- itself was missing, so any database built from `migrations/` kept the old
-- `wallet_address` column and SIWE sign-in could not find `address`.
--
-- Renames `wallet_addresses.wallet_address` to `address` and drops the unused
-- `updated_at`, matching lib/db/schema.ts.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_wallet_addresses` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`address` text NOT NULL,
	`chain_id` integer NOT NULL,
	`is_primary` integer DEFAULT false,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_wallet_addresses`("id", "user_id", "address", "chain_id", "is_primary", "created_at") SELECT "id", "user_id", "wallet_address", "chain_id", "is_primary", "created_at" FROM `wallet_addresses`;--> statement-breakpoint
DROP TABLE `wallet_addresses`;--> statement-breakpoint
ALTER TABLE `__new_wallet_addresses` RENAME TO `wallet_addresses`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `wallet_addresses_address_unique` ON `wallet_addresses` (`address`);
